# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-08 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='webshops.Category')),
            ],
            options={
                'ordering': ('name', '-pk', '-added_at'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reserved', models.BooleanField(default=False)),
                ('name', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_excl_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshops.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.PositiveSmallIntegerField(choices=[(0, 'Stand-alone product'), (1, 'Parent product'), (2, 'Child product')], default=0, verbose_name='Product structure')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('featured', models.BooleanField(default=True, help_text='This product will be displayed on the front page of the shop.', verbose_name='Featured')),
                ('barcode_type', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Code 128'), (2, 'EAN'), (3, 'EAN-8'), (4, 'Code 93'), (5, 'Code 93 VIN'), (6, 'Codabar'), (7, 'UPC'), (8, 'UPC E'), (9, 'Code 25 \u2013 Interleaved 2 of 5'), (10, 'Code 25 \u2013 Non-interleaved 2 of 5'), (11, 'Code 93')], default=0)),
                ('barcode', models.TextField(blank=True)),
                ('pcs_in_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pieces in stock')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price including VAT.', max_digits=8, null=True, verbose_name='Price')),
                ('price_excl_vat', models.DecimalField(blank=True, decimal_places=2, help_text='Price excluding VAT.', max_digits=8, null=True, verbose_name='Price excl VAT')),
                ('vat', models.PositiveIntegerField(choices=[(0, 'None'), (6, 'VAT low (6%)'), (21, 'VAT high (21%)')], default=6, verbose_name='VAT rate')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_discountable', models.BooleanField(default=True, help_text='This flag indicates if this product can be used in an offer or not', verbose_name='Is discountable?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='webshops.Category', verbose_name='Category')),
                ('parent', models.ForeignKey(blank=True, help_text="Only choose a parent product if you're creating a child product.  For example if this is a size 4 of a particular t-shirt.  Leave blank if this is a stand-alone product (i.e. there is only one version of this product).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='webshops.Product', verbose_name='Parent product')),
            ],
            options={
                'ordering': ('-added_at', 'name', 'pk'),
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Webshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('name', models.TextField(verbose_name='Name')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='webshops', to='sites.Site')),
            ],
            options={
                'ordering': ('-active', 'name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='webshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='webshops.Webshop'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshops.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='webshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='webshops.Webshop'),
        ),
        migrations.AddField(
            model_name='category',
            name='webshop',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='webshops.Webshop'),
        ),
    ]
